import { defineConfig } from "tsup";

export default defineConfig({
  entry: [
    "src/index.ts",
    "src/theme/index.tsx",
    "src/theme/tokens.ts",
    "src/relief-card/index.ts",
    "src/avatar/index.ts",
    "src/badge/index.ts",
    "src/box/index.ts",
    "src/button/index.ts",
    "src/card/index.ts",
    "src/checkbox/index.ts",
    "src/collapse/index.ts",
    "src/date-picker/index.ts",
    "src/date-range-picker/index.ts",
    "src/container/index.ts",
    "src/divider/index.ts",
    "src/drawer/index.ts",
    "src/dropdown/index.ts",
    "src/flex/index.ts",
    "src/form/index.ts",
    "src/grid/index.ts",
    "src/input/index.ts",
    "src/list/index.ts",
    "src/modal/index.ts",
    "src/pagination/index.ts",
    "src/popover/index.ts",
    "src/progress/index.ts",
    "src/radio/index.ts",
    "src/select/index.ts",
    "src/skeleton/index.ts",
    "src/spinner/index.ts",
    "src/stack/index.ts",
    "src/switch/index.ts",
    "src/table/index.ts",
    "src/tabs/index.ts",
    "src/tag/index.ts",
    "src/text/index.ts",
    "src/text-area/index.ts",
    "src/toast/index.ts",
    "src/tooltip/index.ts",
    "src/virtual-table/index.ts",
    "src/wizard/index.ts",
    "src/alert/index.ts",
    "src/breadcrumb/index.ts",
    "src/combobox/index.ts",
    "src/slider/index.ts",
  ],
  format: ["esm", "cjs"],
  outExtension: ({ format }) => ({
    js: format === "esm" ? ".mjs" : ".cjs",
  }),
  dts: {
    compilerOptions: {
      composite: false,
    },
  },
  sourcemap: false,
  clean: true,
  treeshake: true,
  splitting: true,
  noExternal: ["@velune/hooks"],
  external: ["react", "react-dom", "clsx", "@tanstack/react-virtual"],
});
